services:
  paintagrid.web:
    image: paintagrid.web
    build:
      context: .
      dockerfile: PaintAGrid.Web/Dockerfile
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password