services:
  paintagrid.web:
    image: paintagrid.web
    build:
      context: csharp
      dockerfile: csharp/PaintAGrid.Web/Dockerfile
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  json-server:
    image: clue/json-server
    ports:
      - "3000:80"
    volumes:
      - .mock-server/grid.json:/data/db.json
    command: json-server --watch /data/db.json --port 80
